
name: CI Sage2Odoo

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Preparar data/ con XML de prueba
        run: |
          mkdir -p data
          cp -r tests/data/* data/

      - name: Ejecutar parser
        run: python -m scripts.main

      - name: Ejecutar tests
        run: pytest
