name: Sage2Odoo CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar parser para generar los CSV
        run: |
          python -m scripts.main \
            --input_folder tests/data \
            --output_folder output \
            --facturas_file MovimientosFacturasTest.xml \
            --asientos_file MovimientosAsientosTest.xml

      - name: Ejecutar tests con pytest
        run: pytest

      - name: Subir artefactos generados (opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-generados
          path: output/
